export interface Student {
  id: number;
  user: number;
  username: string;
  email: string;
  student_id: string;
  usi: string;
  usi_verified: boolean;
  optional_id: string;
  date_of_birth: string | null;
  gender: string;
  mobile_phone: string;
  postal_address: string;
  street_address: string;
  citizen_status: string;
  country_of_birth: string;
  city_of_birth: string;
  citizenship: string;
  indigenous_status: string;
  employment_status: string;
  occupation_identifier: string;
  industry_of_employment: string;
  language: string;
  english_proficiency: string;
  needs_english_assistance: boolean;
  highest_education: string;
  attending_other_school: boolean;
  survey_contact_status: string;
  passport_number: string;
  visa_type: string;
  visa_expiry_date: string | null;
  emergency_contact_name: string;
  emergency_contact_relationship: string;
  emergency_contact_phone: string;
  campus: number;
  campus_name: string;
  enrollment_date: string;
  status: string;
  created_at: string;
  updated_at: string;
  updated_by: number | null;
  updated_by_username: string | null;
}