# Generated by Django 6.1 on 2026-08-23 23:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_course'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('usi', models.CharField(blank=True, max_length=20, verbose_name='USI')),
                ('usi_verified', models.BooleanField(default=False, verbose_name='USI Verified')),
                ('optional_id', models.CharField(blank=True, max_length=50)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other'), ('UNSPECIFIED', 'Prefer not to say')], max_length=20)),
                ('mobile_phone', models.CharField(blank=True, max_length=20)),
                ('postal_address', models.CharField(blank=True, max_length=255)),
                ('street_address', models.CharField(blank=True, max_length=255)),
                ('citizen_status', models.CharField(blank=True, choices=[('AU_CITIZEN', 'Australian Citizen'), ('PERMANENT_RESIDENT', 'Permanent Resident'), ('STUDENT_VISA', 'Student Visa'), ('OTHER_VISA', 'Other Visa')], max_length=30)),
                ('country_of_birth', models.CharField(blank=True, max_length=100)),
                ('city_of_birth', models.CharField(blank=True, max_length=100)),
                ('citizenship', models.CharField(blank=True, max_length=100)),
                ('indigenous_status', models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No'), ('PREFER_NOT_TO_SAY', 'Prefer not to say')], max_length=30)),
                ('employment_status', models.CharField(blank=True, choices=[('FULL_TIME', 'Full-time employee'), ('PART_TIME', 'Part-time employee'), ('SELF_EMPLOYED', 'Self-employed'), ('UNEMPLOYED', 'Unemployed'), ('NOT_IN_LABOUR_FORCE', 'Not in labour force')], max_length=30)),
                ('occupation_identifier', models.CharField(blank=True, max_length=100)),
                ('industry_of_employment', models.CharField(blank=True, max_length=100)),
                ('language', models.CharField(blank=True, max_length=100)),
                ('english_proficiency', models.CharField(blank=True, choices=[('VERY_WELL', 'Spoken Very Well'), ('WELL', 'Spoken Well'), ('NOT_WELL', 'Not Well'), ('NOT_AT_ALL', 'Not at all')], max_length=20)),
                ('needs_english_assistance', models.BooleanField(default=False)),
                ('highest_education', models.CharField(blank=True, max_length=150)),
                ('attending_other_school', models.BooleanField(default=False)),
                ('survey_contact_status', models.CharField(blank=True, choices=[('INCLUDED', 'Included in survey use'), ('EXCLUDED', 'Excluded from survey use')], max_length=20)),
                ('passport_number', models.CharField(blank=True, max_length=50)),
                ('visa_type', models.CharField(blank=True, max_length=100)),
                ('visa_expiry_date', models.DateField(blank=True, null=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=150)),
                ('emergency_contact_relationship', models.CharField(blank=True, max_length=50)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20)),
                ('enrollment_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ON_LEAVE', 'On Leave'), ('GRADUATED', 'Graduated'), ('WITHDRAWN', 'Withdrawn')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='academics.campus')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students_updated', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
